sonar.sources=.
sonar.exclusions=**/vendor/**,**/*_test.go
sonar.test.inclusions=./**/*_test.go
sonar.test.exclusions=./vendor/**
sonar.go.coverage.reportPaths=_output/cover.out
sonar.coverage.exclusions=**/zz_generated*.go,**/fake*.go

